/*
 * File: EventMagnitudeStore.js
 * Date: Sun May 05 2013 13:49:24 GMT-0300 (Hora estándar de Argentina)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EventMagnitudeStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        EventMagnitudeStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'eventMagnitudeStore',
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'agency',
                    type: 'string'
                },
                {
                    name: 'value',
                    type: 'float'
                },
                {
                    name: 'type',
                    type: 'string'
                }
            ]
        }, cfg));
    }
});