/*
 * File: EventStore.js
 * Date: Mon Apr 11 2011 03:14:10 GMT-0300 (Argentina Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

EventStore = Ext.extend(Ext.data.DirectStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        EventStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'eventStore'
        }, cfg));
    }
});
