/*
 * File: LocationEventStore.js
 * Date: Sun May 05 2013 13:49:24 GMT-0300 (Hora estándar de Argentina)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

LocationEventStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        LocationEventStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'locationEventStore',
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'information',
                    type: 'string'
                },
                {
                    name: 'date',
                    type: 'date'
                },
                {
                    name: 'magnitude',
                    type: 'float'
                },
                {
                    name: 'rankmagnitude',
                    type: 'float'
                }
            ]
        }, cfg));
    }
});