/*
 * File: SeismapViewport.ui.js
 * Date: Sun May 05 2013 13:49:24 GMT-0300 (Hora estándar de Argentina)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SeismapViewportUi = Ext.extend(Ext.Viewport, {
    id: 'seismapViewport',
    layout: 'border',

    initComponent: function() {
        Ext.applyIf(this, {
            items: [
                {
                    xtype: 'panel',
                    id: 'mapsPanel',
                    width: 150,
                    buttonAlign: 'left',
                    collapsible: true,
                    title: 'Mapas',
                    collapsible: true,
                    floatable: false,
                    region: 'west',
                    split: true,
                    items: [
                        {
                            xtype: 'treepanel',
                            id: 'mapsTree',
                            autoHeight: true,
                            border: false,
                            buttonAlign: 'left',
                            headerAsText: false,
                            hideCollapseTool: true,
                            rootVisible: false,
                            root: {
                                id: 'categoriesNode',
                                text: 'Categories',
                                children: [
                                    {
                                        expanded: true,
                                        id: '',
                                        text: 'Recientes',
                                        children: [
                                            {
                                                allowChildren: false,
                                                id: 'pais24h',
                                                leaf: true,
                                                text: 'País - Ultimas 24h'
                                            },
                                            {
                                                allowChildren: false,
                                                id: 'cuyo24h',
                                                leaf: true,
                                                text: 'Cuyo - Ultima semana'
                                            }
                                        ]
                                    },
                                    {
                                        expanded: true,
                                        id: '',
                                        text: 'Historicos',
                                        children: [
                                            {
                                                allowChildren: false,
                                                id: 'paisAll',
                                                leaf: true,
                                                text: 'País - todos'
                                            }
                                        ]
                                    }
                                ]
                            },
                            loader: {

                            }
                        }
                    ],
                    tbar: {
                        xtype: 'toolbar',
                        id: 'mapsToolbar',
                        enableOverflow: true,
                        items: [
                            {
                                xtype: 'button',
                                id: 'newMapButton',
                                text: 'Nuevo mapa...'
                            },
                            {
                                xtype: 'button',
                                id: 'renameMapButton',
                                text: 'Renombrar map...'
                            },
                            {
                                xtype: 'button',
                                id: 'changeMapCategoryButton',
                                text: 'Mover mapa de categoria...'
                            }
                        ]
                    }
                },
                {
                    xtype: 'container',
                    id: 'mainToolbarContainer',
                    width: 100,
                    region: 'north',
                    items: [
                        {
                            xtype: 'toolbar',
                            id: 'mainToolbar',
                            forceLayout: true,
                            items: [
                                {
                                    xtype: 'label',
                                    id: 'titleLabel',
                                    autoHeight: true,
                                    text: 'Seismap'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    id: 'loginButton',
                                    autoHeight: true,
                                    text: 'Log in'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    id: 'mapViewPanel',
                    width: 100,
                    layout: 'border',
                    title: 'Map: [map-name]',
                    region: 'center',
                    tbar: {
                        xtype: 'toolbar',
                        id: 'mapToolbar',
                        enableOverflow: true,
                        region: 'center',
                        items: [
                            {
                                xtype: 'button',
                                disabled: true,
                                id: 'saveChangesButton',
                                text: 'Guardar cambios'
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                id: 'discardChangesButton',
                                text: 'Descartar cambios'
                            },
                            {
                                xtype: 'tbseparator'
                            },
                            {
                                xtype: 'button',
                                id: 'saveMapAsButton',
                                text: 'Guardar mapa como..'
                            },
                            {
                                xtype: 'tbseparator'
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                id: 'deleteMapButton',
                                height: 22,
                                text: 'Borrar mapa'
                            },
                            {
                                xtype: 'tbseparator'
                            },
                            {
                                xtype: 'button',
                                id: 'depthMapButton',
                                enableToggle: true,
                                text: 'Mapa de profundidad'
                            },
                            {
                                xtype: 'tbseparator'
                            },
                            {
                                xtype: 'button',
                                id: 'showLegendButton',
                                enableToggle: true,
                                pressed: true,
                                text: 'Mostrar leyenda'
                            }
                        ]
                    },
                    items: [
                        {
                            xtype: 'container',
                            id: 'mapArea',
                            region: 'center'
                        },
                        {
                            xtype: 'panel',
                            id: 'parametersPanel',
                            width: 500,
                            activeItem: 2,
                            layout: 'accordion',
                            collapsible: true,
                            titleCollapse: true,
                            collapsible: true,
                            floatable: false,
                            region: 'east',
                            split: true,
                            items: [
                                {
                                    xtype: 'panel',
                                    id: 'viewPanel',
                                    autoScroll: true,
                                    layout: 'form',
                                    collapsible: true,
                                    padding: 4,
                                    title: 'Vista',
                                    titleCollapse: true,
                                    items: [
                                        {
                                            xtype: 'sliderfield',
                                            id: 'initialZoomControl',
                                            name: 'initialZoom',
                                            value: 1,
                                            maxValue: 21,
                                            anchor: '100%',
                                            fieldLabel: 'Zoom inicial'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            id: 'initialLatitudeControl',
                                            name: 'initialLatitude',
                                            allowBlank: false,
                                            decimalPrecision: 16,
                                            maxValue: 90,
                                            minValue: -90,
                                            anchor: '100%',
                                            fieldLabel: 'Latitud inicial'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            id: 'initialLongitudeControl',
                                            name: 'initialLongitude',
                                            allowBlank: false,
                                            decimalPrecision: 16,
                                            maxValue: 180,
                                            minValue: -180,
                                            anchor: '100%',
                                            fieldLabel: 'Longitud inicial'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'initialViewCompositeField',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    cls: 'linkField',
                                                    id: 'useCurrentViewLink',
                                                    value: 'Usar vista actual',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    cls: 'linkField',
                                                    id: 'showInitialViewLink',
                                                    value: 'Mostrar vista inicial',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'combo',
                                            id: 'styleCombo',
                                            name: 'style',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            forceSelection: true,
                                            lazyInit: false,
                                            mode: 'local',
                                            store: 'styleStore',
                                            triggerAction: 'all',
                                            valueField: 'id',
                                            anchor: '100%',
                                            fieldLabel: 'Estilo'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'filtersPanel',
                                    autoScroll: true,
                                    layout: 'form',
                                    collapsible: true,
                                    maskDisabled: false,
                                    padding: 4,
                                    title: 'Filtro',
                                    titleCollapse: true,
                                    items: [
                                        {
                                            xtype: 'radio',
                                            id: 'dateMinModeNoneRadio',
                                            name: 'dateMinMode',
                                            boxLabel: 'Siempre',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Desde'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'dateMinModeRelativeCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'dateMinModeRelativeRadio',
                                                    name: 'dateMinMode',
                                                    boxLabel: '',
                                                    inputValue: 'relative',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'dateMinRelativeHeadingLabel',
                                                    value: 'Hace',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'dateMinRelativeAmountField',
                                                    width: 50,
                                                    name: 'dateMinRelativeAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'combo',
                                                    id: 'dateMinRelativeUnitsCombo',
                                                    itemId: 'id',
                                                    width: 70,
                                                    name: 'dateMinRelativeUnits',
                                                    allowBlank: false,
                                                    editable: false,
                                                    displayField: 'name',
                                                    forceSelection: true,
                                                    lazyInit: false,
                                                    mode: 'local',
                                                    store: 'dateUnitsStore',
                                                    triggerAction: 'all',
                                                    valueField: 'id',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    hidden: true,
                                                    id: 'dateMinRelativeTrailingLabel',
                                                    value: 'ago',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'dateMinModeAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'dateMinModeAbsoluteRadio',
                                                    name: 'dateMinMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    id: 'dateMinAbsoluteDateField',
                                                    width: 100,
                                                    name: 'dateMinAbsoluteDate',
                                                    allowBlank: false,
                                                    editable: false,
                                                    format: 'd/m/Y',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    id: 'dateMinAbsoluteTimeField',
                                                    width: 80,
                                                    name: 'dateMinAbsoluteTime',
                                                    allowBlank: false,
                                                    editable: false,
                                                    format: 'h:i a',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'dateMaxModeNoneRadio',
                                            name: 'dateMaxMode',
                                            boxLabel: 'Ahora',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Hasta'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'dateMaxModeRelativeCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'dateMaxModeRelativeRadio',
                                                    name: 'dateMaxMode',
                                                    boxLabel: '',
                                                    inputValue: 'relative',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'dateMaxRelativeHeadingLabel',
                                                    value: 'Hace',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'dateMaxRelativeAmountField',
                                                    width: 50,
                                                    name: 'dateMaxRelativeAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'combo',
                                                    id: 'dateMaxRelativeUnitsCombo',
                                                    itemId: 'id',
                                                    width: 70,
                                                    name: 'dateMaxRelativeUnits',
                                                    allowBlank: false,
                                                    editable: false,
                                                    displayField: 'name',
                                                    forceSelection: true,
                                                    lazyInit: false,
                                                    mode: 'local',
                                                    store: 'dateUnitsStore',
                                                    triggerAction: 'all',
                                                    valueField: 'id',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    hidden: true,
                                                    id: 'dateMaxRelativeTrailingLabel',
                                                    value: 'ago',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'dateMaxModeAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'dateMaxModeAbsoluteRadio',
                                                    name: 'dateMaxMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    id: 'dateMaxAbsoluteDateField',
                                                    width: 100,
                                                    name: 'dateMaxAbsoluteDate',
                                                    allowBlank: false,
                                                    editable: false,
                                                    format: 'd/m/Y',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    id: 'dateMaxAbsoluteTimeField',
                                                    autoWidth: true,
                                                    width: 80,
                                                    name: 'dateMaxAbsoluteTime',
                                                    allowBlank: false,
                                                    editable: false,
                                                    format: 'h:i a',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'depthMinModeNoneRadio',
                                            name: 'depthMinMode',
                                            boxLabel: 'La superficie',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Desde'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'depthMinAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'depthMinModeAbsoluteRadio',
                                                    name: 'depthMinMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'depthMinAbsoluteAmountField',
                                                    width: 50,
                                                    name: 'depthMinAbsoluteAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'depthMinAbsoluteUnitsLabel',
                                                    value: 'km',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'depthMaxModeNoneRadio',
                                            name: 'depthMaxMode',
                                            boxLabel: 'Las profundidades',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Hasta'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'depthMaxAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'depthMaxModeAbsoluteRadio',
                                                    name: 'depthMaxMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'depthMaxAbsoluteAmountField',
                                                    width: 50,
                                                    name: 'depthMaxAbsoluteAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'depthMaxModeAbsoluteUnitsLabel',
                                                    value: 'km',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'combo',
                                            id: 'magnitudeScaleCombo',
                                            name: 'magnitudeScale',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            forceSelection: true,
                                            lazyInit: false,
                                            mode: 'local',
                                            store: 'magnitudeTypeStore',
                                            triggerAction: 'all',
                                            valueField: 'id',
                                            anchor: '100%',
                                            fieldLabel: 'Escala'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'magnitudeMinModeNoneRadio',
                                            name: 'magnitudeMinMode',
                                            boxLabel: 'Lo mas suave',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Desde'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'magnitudeMinAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'magnitudeMinModeAbsoluteRadio',
                                                    name: 'magnitudeMinMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'magnitudeMinAbsoluteAmountField',
                                                    width: 50,
                                                    name: 'magnitudeMinAbsoluteAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'magnitudeMinAbsoluteUnitsLabel',
                                                    value: 'unidades de la escala',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'magnitudeMaxModeNoneRadio',
                                            name: 'magnitudeMaxMode',
                                            boxLabel: 'Lo mas intenso',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Hasta'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'magnitudeMaxAbsoluteCompositeField',
                                            fieldClass: 'x-form-field seismap-radio-composite-field',
                                            anchor: '100%',
                                            fieldLabel: ' ',
                                            labelSeparator: ' ',
                                            items: [
                                                {
                                                    xtype: 'radio',
                                                    id: 'magnitudeMaxModeAbsoluteRadio',
                                                    name: 'magnitudeMaxMode',
                                                    boxLabel: '',
                                                    inputValue: 'absolute',
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    id: 'magnitudeMaxAbsoluteAmountField',
                                                    width: 50,
                                                    name: 'magnitudeMinAbsoluteAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    id: 'magnitudeMaxAbsoluteUnitsLabel',
                                                    value: 'unidades de la escala',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'checkbox',
                                            id: 'magnitudeUnmeasuredVisibilityCheckbox',
                                            name: 'magnitudeUnmeasuredVisibility',
                                            boxLabel: 'Mostrar igualmente',
                                            checked: true,
                                            inputValue: 'true',
                                            anchor: '100%',
                                            fieldLabel: 'No medidos'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    id: 'animationPanel',
                                    autoScroll: true,
                                    layout: 'form',
                                    padding: 4,
                                    title: 'Animación',
                                    items: [
                                        {
                                            xtype: 'radio',
                                            id: 'animationByNoneRadio',
                                            name: 'animationBy',
                                            boxLabel: 'Nada',
                                            checked: true,
                                            inputValue: 'none',
                                            anchor: '100%',
                                            fieldLabel: 'Por'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'animationByDateRadio',
                                            name: 'animationBy',
                                            boxLabel: 'Fecha',
                                            inputValue: 'date',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'animationByDepthRadio',
                                            name: 'animationBy',
                                            boxLabel: 'Profundidad',
                                            inputValue: 'depth',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'radio',
                                            id: 'animationByMagnitudeRadio',
                                            name: 'animationBy',
                                            boxLabel: 'Magnitud',
                                            inputValue: 'magnitude',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'animationStepCompositeField',
                                            anchor: '100%',
                                            fieldLabel: 'Cuadros',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    disabled: true,
                                                    id: 'animationStepAmountField',
                                                    width: 50,
                                                    fieldClass: 'x-form-field seismap-animation-field',
                                                    name: 'animationStepAmount',
                                                    value: 1,
                                                    allowBlank: false,
                                                    allowDecimals: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'animationDurationCompositeField',
                                            anchor: '100%',
                                            fieldLabel: 'Duración',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    disabled: true,
                                                    id: 'animationDurationField',
                                                    width: 50,
                                                    fieldClass: 'x-form-field seismap-animation-field',
                                                    name: 'animationKeepPreviousAmount',
                                                    value: 30,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    disabled: true,
                                                    id: 'animationDurationTrailingLabel',
                                                    fieldClass: 'x-form-display-field seismap-animation-field',
                                                    value: 'segundos',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'compositefield',
                                            id: 'animationKeepModePreviousCompositeField',
                                            anchor: '100%',
                                            fieldLabel: 'Preservar',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    disabled: true,
                                                    id: 'animationKeepPreviousAmountField',
                                                    width: 50,
                                                    fieldClass: 'x-form-field seismap-animation-field',
                                                    name: 'animationKeepPreviousAmount',
                                                    value: 30,
                                                    allowBlank: false,
                                                    allowNegative: false,
                                                    fieldLabel: 'Label'
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    disabled: true,
                                                    id: 'animationKeepModePreviousTrailingLabel',
                                                    fieldClass: 'x-form-display-field seismap-animation-field',
                                                    value: '% del cuadro anterior',
                                                    fieldLabel: 'Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'displayfield',
                                            anchor: '100%'
                                        },
                                        {
                                            xtype: 'checkbox',
                                            id: 'reverseAnimationCheckbox',
                                            name: 'reverseAnimation',
                                            boxLabel: 'Inversa',
                                            anchor: '100%',
                                            fieldLabel: 'Dirección'
                                        }
                                    ]
                                }
                            ],
                            bbar: {
                                xtype: 'toolbar',
                                buttonAlign: 'right',
                                items: [
                                    {
                                        xtype: 'button',
                                        id: 'applyButton',
                                        scale: 'medium',
                                        text: 'Aplicar'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        });

        SeismapViewportUi.superclass.initComponent.call(this);
    }
});