/*
 * File: SeismapViewport.js
 * Date: Mon Apr 11 2011 06:05:31 GMT-0300 (Argentina Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

SeismapViewport = Ext.extend(SeismapViewportUi, {
    initComponent: function() {
        SeismapViewport.superclass.initComponent.call(this);
    }
});
