/*
 * File: xds_index.js
 * Date: Sun May 05 2013 13:49:24 GMT-0300 (Hora estándar de Argentina)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var store = new DateUnitsStore();
    var store = new MagnitudeTypeStore();
    var store = new StyleStore();
    var store = new LocationEventStore();
    var store = new EventMagnitudeStore();
    var cmp1 = new SeismapViewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
