/*
 * File: xds_index.js
 * Date: Tue Apr 12 2011 20:56:23 GMT-0300 (Argentina Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new SeismapViewport({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
