/*
 * File: SeismapViewport.ui.js
 * Date: Mon Apr 11 2011 02:10:00 GMT-0300 (Argentina Standard Time)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

SeismapViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    height: 723,
    id: 'seismapViewport',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Mapas',
                collapsible: true,
                buttonAlign: 'left',
                floatable: false,
                region: 'west',
                width: 150,
                split: true,
                id: 'mapsPanel',
                items: [
                    {
                        xtype: 'treepanel',
                        border: false,
                        headerAsText: false,
                        rootVisible: false,
                        autoHeight: true,
                        buttonAlign: 'left',
                        hideCollapseTool: true,
                        region: 'center',
                        id: 'mapsTree',
                        root: {
                            text: 'Categories',
                            id: 'categoriesNode',
                            children: [
                                {
                                    text: 'Recientes',
                                    expanded: true,
                                    id: '',
                                    children: [
                                        {
                                            text: 'País - Últimas 24hs',
                                            allowChildren: false,
                                            leaf: true,
                                            id: 62853
                                        },
                                        {
                                            text: 'Cuyo - Última semana',
                                            allowChildren: false,
                                            leaf: true,
                                            id: 62852
                                        }
                                    ]
                                },
                                {
                                    text: 'Historicos',
                                    expanded: true,
                                    id: '',
                                    children: [
                                        {
                                            text: 'País - todos',
                                            allowChildren: false,
                                            leaf: true,
                                            id: 62851
                                        }
                                    ]
                                }
                            ]
                        },
                        loader: {

                        }
                    }
                ],
                tbar: {
                    xtype: 'toolbar',
                    enableOverflow: true,
                    id: 'mapsToolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Nuevo mapa...',
                            id: 'newMapButton'
                        },
                        {
                            xtype: 'button',
                            text: 'Renombrar map...',
                            id: 'renameMapButton'
                        },
                        {
                            xtype: 'button',
                            text: 'Mover mapa de categoria...',
                            id: 'changeMapCategoryButton'
                        }
                    ]
                }
            },
            {
                xtype: 'container',
                region: 'north',
                width: 100,
                id: 'mainToolbarContainer',
                items: [
                    {
                        xtype: 'toolbar',
                        forceLayout: true,
                        id: 'mainToolbar',
                        items: [
                            {
                                xtype: 'label',
                                text: 'Seismap',
                                autoHeight: true,
                                id: 'titleLabel'
                            },
                            {
                                xtype: 'tbfill'
                            },
                            {
                                xtype: 'button',
                                text: 'Log in',
                                autoHeight: true,
                                id: 'loginButton'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Map: [map-name]',
                region: 'center',
                width: 100,
                layout: 'border',
                id: 'mapViewPanel',
                tbar: {
                    xtype: 'toolbar',
                    enableOverflow: true,
                    id: 'mapToolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Guardar cambios',
                            disabled: true,
                            id: 'saveChangesButton'
                        },
                        {
                            xtype: 'button',
                            text: 'Descartar cambios',
                            disabled: true,
                            id: 'discardChangesButton'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar mapa como..',
                            id: 'saveMapAsButton'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Borrar mapa',
                            height: 22,
                            disabled: true,
                            id: 'deleteMapButton'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Mapa de profundidad',
                            enableToggle: true,
                            id: 'depthMapButton'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Mostrar leyenda',
                            enableToggle: true,
                            pressed: true,
                            id: 'showLegendButton'
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'container',
                        region: 'center',
                        id: 'mapArea'
                    },
                    {
                        xtype: 'panel',
                        width: 500,
                        layout: 'accordion',
                        collapsible: true,
                        titleCollapse: true,
                        region: 'east',
                        split: true,
                        floatable: false,
                        activeItem: 2,
                        id: 'parametersPanel',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Vista',
                                collapsible: true,
                                titleCollapse: true,
                                layout: 'form',
                                padding: 4,
                                autoScroll: true,
                                id: 'viewPanel',
                                items: [
                                    {
                                        xtype: 'sliderfield',
                                        value: 1,
                                        fieldLabel: 'Zoom inicial',
                                        anchor: '100%',
                                        name: 'initialZoom',
                                        maxValue: 21,
                                        id: 'initialZoomControl'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        fieldLabel: 'Latitud inicial',
                                        anchor: '100%',
                                        name: 'initialLatitude',
                                        minValue: -90,
                                        maxValue: 90,
                                        decimalPrecision: 16,
                                        allowBlank: false,
                                        id: 'initialLatitudeControl'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        fieldLabel: 'Longitud inicial',
                                        anchor: '100%',
                                        name: 'initialLongitude',
                                        minValue: -180,
                                        maxValue: 180,
                                        decimalPrecision: 16,
                                        allowBlank: false,
                                        id: 'initialLongitudeControl'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        anchor: '100%',
                                        id: 'initialViewCompositeField',
                                        items: [
                                            {
                                                xtype: 'displayfield',
                                                value: 'Usar vista actual',
                                                margins: '2px 5px 0px -1px',
                                                cls: 'linkField',
                                                fieldLabel: 'Label',
                                                id: 'useCurrentViewLink'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'Mostrar vista inicial',
                                                margins: '2px 5px 0px 10px',
                                                cls: 'linkField',
                                                fieldLabel: 'Label',
                                                id: 'showInitialViewLink'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'combo',
                                        fieldLabel: 'Estilo',
                                        anchor: '100%',
                                        name: 'style',
                                        store: 'styleStore',
                                        triggerAction: 'all',
                                        allowBlank: false,
                                        valueField: 'id',
                                        displayField: 'name',
                                        editable: false,
                                        lazyInit: false,
                                        forceSelection: true,
                                        mode: 'local',
                                        id: 'styleCombo'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Filtro',
                                collapsible: true,
                                titleCollapse: true,
                                layout: 'form',
                                autoScroll: true,
                                padding: 4,
                                maskDisabled: false,
                                id: 'filtersPanel',
                                items: [
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Siempre',
                                        checked: true,
                                        name: 'dateMinMode',
                                        fieldLabel: 'Desde',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'dateMinModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'dateMinModeRelativeCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'dateMinMode',
                                                inputValue: 'relative',
                                                fieldLabel: 'Label',
                                                id: 'dateMinModeRelativeRadio'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'Hace',
                                                margins: '2px 5px 0px -1px',
                                                fieldLabel: 'Label',
                                                id: 'dateMinRelativeHeadingLabel'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'dateMinRelativeAmount',
                                                allowBlank: false,
                                                allowNegative: false,
                                                fieldLabel: 'Label',
                                                id: 'dateMinRelativeAmountField'
                                            },
                                            {
                                                xtype: 'combo',
                                                allowBlank: false,
                                                editable: false,
                                                width: 70,
                                                store: 'dateUnitsStore',
                                                name: 'dateMinRelativeUnits',
                                                itemId: 'id',
                                                valueField: 'id',
                                                displayField: 'name',
                                                triggerAction: 'all',
                                                forceSelection: true,
                                                lazyInit: false,
                                                mode: 'local',
                                                fieldLabel: 'Label',
                                                id: 'dateMinRelativeUnitsCombo'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'ago',
                                                margins: '2px 0px 0px 0px',
                                                hidden: true,
                                                fieldLabel: 'Label',
                                                id: 'dateMinRelativeTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        anchor: '100%',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        id: 'dateMinModeAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'dateMinMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'dateMinModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'datefield',
                                                name: 'dateMinAbsoluteDate',
                                                allowBlank: false,
                                                width: 100,
                                                editable: false,
                                                format: 'd/m/Y',
                                                fieldLabel: 'Label',
                                                id: 'dateMinAbsoluteDateField'
                                            },
                                            {
                                                xtype: 'timefield',
                                                width: 80,
                                                name: 'dateMinAbsoluteTime',
                                                allowBlank: false,
                                                editable: false,
                                                format: 'h:i a',
                                                fieldLabel: 'Label',
                                                id: 'dateMinAbsoluteTimeField'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Ahora',
                                        checked: true,
                                        name: 'dateMaxMode',
                                        fieldLabel: 'Hasta',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'dateMaxModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'dateMaxModeRelativeCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'dateMaxMode',
                                                inputValue: 'relative',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxModeRelativeRadio'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'Hace',
                                                margins: '2px 5px 0px -1px',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxRelativeHeadingLabel'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'dateMaxRelativeAmount',
                                                allowBlank: false,
                                                allowNegative: false,
                                                fieldLabel: 'Label',
                                                id: 'dateMaxRelativeAmountField'
                                            },
                                            {
                                                xtype: 'combo',
                                                allowBlank: false,
                                                editable: false,
                                                width: 70,
                                                store: 'dateUnitsStore',
                                                name: 'dateMaxRelativeUnits',
                                                itemId: 'id',
                                                valueField: 'id',
                                                displayField: 'name',
                                                triggerAction: 'all',
                                                forceSelection: true,
                                                lazyInit: false,
                                                mode: 'local',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxRelativeUnitsCombo'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'ago',
                                                margins: '2px 0px 0px 0px',
                                                hidden: true,
                                                fieldLabel: 'Label',
                                                id: 'dateMaxRelativeTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        anchor: '100%',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        id: 'dateMaxModeAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'dateMaxMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'datefield',
                                                name: 'dateMaxAbsoluteDate',
                                                width: 100,
                                                allowBlank: false,
                                                editable: false,
                                                format: 'd/m/Y',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxAbsoluteDateField'
                                            },
                                            {
                                                xtype: 'timefield',
                                                autoWidth: true,
                                                width: 80,
                                                name: 'dateMaxAbsoluteTime',
                                                allowBlank: false,
                                                editable: false,
                                                format: 'h:i a',
                                                fieldLabel: 'Label',
                                                id: 'dateMaxAbsoluteTimeField'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'La superficie',
                                        checked: true,
                                        name: 'depthMinMode',
                                        fieldLabel: 'Desde',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'depthMinModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'depthMinAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'depthMinMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'depthMinModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'depthMinAbsoluteAmount',
                                                allowNegative: false,
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'depthMinAbsoluteAmountField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'km',
                                                margins: '2px 0px 0px 0px',
                                                fieldLabel: 'Label',
                                                id: 'depthMinAbsoluteUnitsLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Las profundidades',
                                        checked: true,
                                        name: 'depthMaxMode',
                                        fieldLabel: 'Hasta',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'depthMaxModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'depthMaxAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'depthMaxMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'depthMaxModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'depthMaxAbsoluteAmount',
                                                allowNegative: false,
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'depthMaxAbsoluteAmountField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'km',
                                                margins: '2px 0px 0px 0px',
                                                fieldLabel: 'Label',
                                                id: 'depthMaxModeAbsoluteUnitsLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'combo',
                                        fieldLabel: 'Escala',
                                        anchor: '100%',
                                        name: 'magnitudeScale',
                                        store: 'magnitudeTypeStore',
                                        triggerAction: 'all',
                                        allowBlank: false,
                                        valueField: 'id',
                                        displayField: 'name',
                                        editable: false,
                                        lazyInit: false,
                                        forceSelection: true,
                                        mode: 'local',
                                        id: 'magnitudeScaleCombo'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Lo mas suave',
                                        checked: true,
                                        name: 'magnitudeMinMode',
                                        fieldLabel: 'Desde',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'magnitudeMinModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'magnitudeMinAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'magnitudeMinMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMinModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'magnitudeMinAbsoluteAmount',
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMinAbsoluteAmountField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'unidades de la escala',
                                                margins: '2px 0px 0px 0px',
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMinAbsoluteUnitsLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Lo mas intenso',
                                        checked: true,
                                        name: 'magnitudeMaxMode',
                                        fieldLabel: 'Hasta',
                                        inputValue: 'none',
                                        anchor: '100%',
                                        id: 'magnitudeMaxModeNoneRadio'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: ' ',
                                        labelSeparator: ' ',
                                        fieldClass: 'x-form-field seismap-radio-composite-field',
                                        anchor: '100%',
                                        id: 'magnitudeMaxAbsoluteCompositeField',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: '',
                                                name: 'magnitudeMaxMode',
                                                inputValue: 'absolute',
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMaxModeAbsoluteRadio'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                value: 1,
                                                width: 50,
                                                name: 'magnitudeMinAbsoluteAmount',
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMaxAbsoluteAmountField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'unidades de la escala',
                                                margins: '2px 0px 0px 0px',
                                                fieldLabel: 'Label',
                                                id: 'magnitudeMaxAbsoluteUnitsLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'checkbox',
                                        fieldLabel: 'No medidos',
                                        boxLabel: 'Mostrar igualmente',
                                        anchor: '100%',
                                        name: 'magnitudeUnmeasuredVisibility',
                                        inputValue: 'true',
                                        checked: true,
                                        id: 'magnitudeUnmeasuredVisibilityCheckbox'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Animación',
                                layout: 'form',
                                padding: 4,
                                autoScroll: true,
                                id: 'animationPanel',
                                items: [
                                    {
                                        xtype: 'radio',
                                        fieldLabel: 'Por',
                                        boxLabel: 'Nada',
                                        anchor: '100%',
                                        name: 'animationBy',
                                        checked: true,
                                        inputValue: 'none',
                                        id: 'animationByNoneRadio'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Fecha',
                                        anchor: '100%',
                                        name: 'animationBy',
                                        inputValue: 'date',
                                        id: 'animationByDateRadio'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Profundidad',
                                        anchor: '100%',
                                        name: 'animationBy',
                                        inputValue: 'depth',
                                        id: 'animationByDepthRadio'
                                    },
                                    {
                                        xtype: 'radio',
                                        boxLabel: 'Magnitud',
                                        anchor: '100%',
                                        name: 'animationBy',
                                        inputValue: 'magnitude',
                                        id: 'animationByMagnitudeRadio'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Cuadros',
                                        anchor: '100%',
                                        id: 'animationStepCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                width: 50,
                                                value: 1,
                                                name: 'animationStepAmount',
                                                disabled: true,
                                                fieldClass: 'x-form-field seismap-animation-field',
                                                allowBlank: false,
                                                allowNegative: false,
                                                allowDecimals: false,
                                                fieldLabel: 'Label',
                                                id: 'animationStepAmountField'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Duración',
                                        anchor: '100%',
                                        id: 'animationDurationCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                width: 50,
                                                value: 30,
                                                name: 'animationKeepPreviousAmount',
                                                disabled: true,
                                                fieldClass: 'x-form-field seismap-animation-field',
                                                allowNegative: false,
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'animationDurationField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'segundos',
                                                disabled: true,
                                                margins: '2px 0px 0px 2px',
                                                fieldClass: 'x-form-display-field seismap-animation-field',
                                                fieldLabel: 'Label',
                                                id: 'animationDurationTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Preservar',
                                        anchor: '100%',
                                        id: 'animationKeepModePreviousCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                width: 50,
                                                value: 30,
                                                name: 'animationKeepPreviousAmount',
                                                disabled: true,
                                                fieldClass: 'x-form-field seismap-animation-field',
                                                allowNegative: false,
                                                allowBlank: false,
                                                fieldLabel: 'Label',
                                                id: 'animationKeepPreviousAmountField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: '% del cuadro anterior',
                                                disabled: true,
                                                margins: '2px 0px 0px 2px',
                                                fieldClass: 'x-form-display-field seismap-animation-field',
                                                fieldLabel: 'Label',
                                                id: 'animationKeepModePreviousTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'checkbox',
                                        fieldLabel: 'Dirección',
                                        boxLabel: 'Inversa',
                                        anchor: '100%',
                                        name: 'reverseAnimation',
                                        id: 'reverseAnimationCheckbox'
                                    }
                                ]
                            }
                        ],
                        bbar: {
                            xtype: 'toolbar',
                            buttonAlign: 'right',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Aplicar',
                                    scale: 'medium',
                                    id: 'applyButton'
                                }
                            ]
                        }
                    }
                ]
            },
            {
                xtype: 'window',
                title: 'Sismo: [event-information]',
                width: 620,
                height: 380,
                floating: true,
                autoHide: false,
                closeAction: 'hide',
                maximizable: true,
                layout: 'border',
                modal: true,
                id: 'eventWindow',
                items: [
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        region: 'center',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Mapa',
                                layout: 'border',
                                id: 'eventMapTab',
                                items: [
                                    {
                                        xtype: 'container',
                                        region: 'center',
                                        id: 'eventMapArea'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Magnitudes',
                                layout: 'border',
                                id: 'eventMagnitudesTab',
                                items: [
                                    {
                                        xtype: 'grid',
                                        store: 'eventMagnitudeStore',
                                        region: 'center',
                                        id: 'eventMagnitudesGrid',
                                        selModel: new Ext.grid.RowSelectionModel({
                                            singleSelect: true
                                        }),
                                        columns: [
                                            {
                                                xtype: 'numbercolumn',
                                                dataIndex: 'id',
                                                header: 'Id',
                                                sortable: true,
                                                width: 60,
                                                align: 'right',
                                                groupable: false,
                                                format: '0',
                                                id: 'eventMagnitudesIdColumn'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'agency',
                                                header: 'Agencia',
                                                sortable: true,
                                                width: 60,
                                                id: 'eventMagnitudesAgencyColumn'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                header: 'Valor',
                                                sortable: true,
                                                width: 60,
                                                align: 'right',
                                                dataIndex: 'value',
                                                format: '0.000,00/i',
                                                id: 'eventMagnitudesValueColumn'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'type',
                                                header: 'Tipo',
                                                sortable: true,
                                                width: 200,
                                                id: 'eventMagnitudesTypeColumn'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        width: 320,
                        layout: 'accordion',
                        activeItem: 0,
                        collapsible: true,
                        titleCollapse: true,
                        region: 'east',
                        split: true,
                        id: 'eventPanel',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Información',
                                layout: 'form',
                                padding: 4,
                                autoScroll: true,
                                id: 'eventInformationPanel',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        name: 'ventName',
                                        fieldLabel: 'Nombre',
                                        anchor: '100%',
                                        id: 'eventNameField'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Fecha',
                                        id: 'eventDateCompositeField',
                                        items: [
                                            {
                                                xtype: 'datefield',
                                                name: 'eventDateDate',
                                                allowBlank: false,
                                                width: 100,
                                                editable: false,
                                                format: 'd/m/Y',
                                                fieldLabel: 'Label',
                                                readOnly: true,
                                                id: 'eventDateDateField'
                                            },
                                            {
                                                xtype: 'timefield',
                                                width: 80,
                                                name: 'eventDateTime',
                                                allowBlank: false,
                                                editable: false,
                                                increment: 1,
                                                format: 'h:i a',
                                                fieldLabel: 'Label',
                                                readOnly: true,
                                                id: 'eventDateTimeField'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'textfield',
                                        fieldLabel: 'Referencia',
                                        anchor: '100%',
                                        name: 'eventReference',
                                        id: 'eventReferenceField'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        fieldLabel: 'Magnitud',
                                        anchor: '100%',
                                        name: 'eventMagnitude',
                                        readOnly: true,
                                        id: 'eventMagnitudeField'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        fieldLabel: 'Ranking',
                                        anchor: '100%',
                                        name: 'eventRankMagnitude',
                                        readOnly: true,
                                        id: 'eventRankMagnitudeField'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Profundidad',
                                        anchor: '100%',
                                        id: 'eventDepthCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                name: 'eventDepth',
                                                readOnly: true,
                                                flex: 1,
                                                id: 'eventDepthField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'km',
                                                flex: 1,
                                                fieldLabel: 'Label',
                                                id: 'eventDepthTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'textarea',
                                        anchor: '100%',
                                        fieldLabel: 'Descripción',
                                        name: 'eventNotes',
                                        id: 'eventNotesArea'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                title: 'Adicional',
                                layout: 'form',
                                padding: 4,
                                autoScroll: true,
                                id: 'eventIAditionalPanel',
                                items: [
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Distancia percibida',
                                        anchor: '100%',
                                        id: 'eventPerceivedDistanceCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                name: 'eventPerceivedDistanceRadius',
                                                flex: 1,
                                                id: 'eventPerceivedDistanceField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'km',
                                                flex: 1,
                                                fieldLabel: 'Label',
                                                id: 'eventPerceivedDistanceTrailingLabel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'displayfield',
                                        anchor: '100%'
                                    },
                                    {
                                        xtype: 'compositefield',
                                        fieldLabel: 'Distancia de daños',
                                        id: 'eventDamagedDistanceCompositeField',
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                name: 'eventDamagedDistance',
                                                flex: 1,
                                                id: 'eventDamagedDistanceField'
                                            },
                                            {
                                                xtype: 'displayfield',
                                                value: 'km',
                                                flex: 1,
                                                id: 'eventDamagedDistanceTrailingLabel'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    buttonAlign: 'right',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cerrar',
                            scale: 'medium',
                            id: 'eventCloseButton'
                        },
                        {
                            xtype: 'button',
                            text: 'Guardar',
                            scale: 'medium',
                            id: 'eventSaveButton'
                        }
                    ]
                }
            },
            {
                xtype: 'window',
                title: 'Mapa de profundidad',
                width: 660,
                height: 420,
                floating: true,
                autoHide: false,
                closeAction: 'hide',
                maximizable: true,
                layout: 'border',
                modal: true,
                floatable: false,
                id: 'depthWindow',
                items: [
                    {
                        xtype: 'container',
                        region: 'center',
                        id: 'depthMapArea'
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    buttonAlign: 'right',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cerrar',
                            scale: 'medium',
                            id: 'depthCloseButton'
                        }
                    ]
                }
            },
            {
                xtype: 'window',
                title: 'Leyenda',
                width: 311,
                height: 201,
                floating: true,
                hidden: false,
                initHidden: false,
                autoHide: false,
                closeAction: 'hide',
                layout: 'border',
                floatable: false,
                resizable: false,
                id: 'legendWindow',
                items: [
                    {
                        xtype: 'container',
                        region: 'center',
                        id: 'legendImage'
                    }
                ]
            },
            {
                xtype: 'window',
                title: 'Sismos en esa ubicación',
                width: 620,
                height: 360,
                floating: true,
                autoHide: false,
                modal: true,
                layout: 'border',
                closeAction: 'hide',
                defaultButton: 'locationEventsDetailsButton',
                maximizable: true,
                undefined: 100,
                id: 'locationEventsWindow',
                items: [
                    {
                        xtype: 'grid',
                        store: 'locationEventStore',
                        region: 'center',
                        id: 'locationEventsGrid',
                        selModel: new Ext.grid.RowSelectionModel({
                            singleSelect: true
                        }),
                        columns: [
                            {
                                xtype: 'numbercolumn',
                                dataIndex: 'id',
                                header: 'Id',
                                sortable: true,
                                width: 60,
                                align: 'right',
                                groupable: false,
                                format: '0',
                                id: 'locationEventsIdColumn'
                            },
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'information',
                                header: 'Información',
                                sortable: true,
                                width: 275,
                                id: 'locationEventsInformationColumn'
                            },
                            {
                                xtype: 'datecolumn',
                                dataIndex: 'date',
                                header: 'Fecha',
                                sortable: true,
                                width: 126,
                                format: 'd/m/Y h:i:s a',
                                id: 'locationEventsDateColumn'
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Magnitud',
                                sortable: true,
                                width: 60,
                                align: 'right',
                                dataIndex: 'magnitude',
                                format: '0.000,00/i',
                                id: 'locationEventsMagnitudeColumn'
                            },
                            {
                                xtype: 'numbercolumn',
                                header: 'Ranking',
                                sortable: true,
                                width: 60,
                                align: 'right',
                                dataIndex: 'rankmagnitude',
                                format: '0.000,00/i',
                                id: 'locationEventsRankMagnitudeColumn'
                            }
                        ]
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    buttonAlign: 'right',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Cerrar',
                            scale: 'medium',
                            id: 'locationEventsCloseButton'
                        },
                        {
                            xtype: 'button',
                            text: 'Detalles',
                            scale: 'medium',
                            disabled: true,
                            id: 'locationEventsDetailsButton'
                        }
                    ]
                }
            }
        ];
        SeismapViewportUi.superclass.initComponent.call(this);
    }
});
